enable-experiment:
  - extension-methods

#https://gist.github.com/tomaszpolanski/ec89aee4b7fc8905c48ce0d3c246bf71
#https://dart-lang.github.io/linter/lints/
analyzer:
  errors:
    always_use_package_imports: error
    avoid_print: warning
    avoid_returning_null_for_future: warning
    always_declare_return_types: warning
    always_specify_types: warning
    avoid_return_types_on_setters: warning
    missing_required_param: error
    missing_return: error
  language:
    strict-inference: true


linter:
  rules:
    always_use_package_imports: true
    avoid_print: false
    avoid_returning_null_for_future: false
    always_declare_return_types: true
    always_specify_types: false
    avoid_return_types_on_setters: true
    //always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    prefer_const_declarations: true
    avoid_renaming_method_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    //await_only_futures: true
    curly_braces_in_flow_control_structures: false
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: false;
    no_adjacent_strings_in_list: true;
    no_duplicate_case_values: true;
    no_logic_in_create_state: true;
    no_runtimeType_toString: true;
    non_constant_identifier_names: true;
    null_closures: true;
    only_throw_errors: true;
    overridden_fields: true;
    prefer_conditional_assignment: true;
    prefer_const_constructors: true;
    prefer_equal_for_default_values: true;
    prefer_final_fields: true;
    prefer_final_in_for_each: true;
    prefer_final_locals: true;
    sort_unnamed_constructors_first: true;
    test_types_in_equals: true;
    unawaited_futures: true;
    unnecessary_await_in_return: true;
    unnecessary_getters_setters: true;
    unnecessary_new: true;
    unnecessary_overrides: true;
    unnecessary_parenthesis: true;
    use_setters_to_change_properties: true;


