name: logos_maru
description: Language Translation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0+4
  http: ^0.13.3
  package_info_plus: ^1.3.0
  google_fonts: ^3.0.1
  flutter_lint_rules:
    git:
      url: https://github.com/polyGeek/flutter_lint_rules
      revision: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/.
    - assets/logos_maru/.
    - assets/logos_maru/flags/.

#    - assets/logosmaru/logos_EN.db
#    - assets/logosmaru/logos_ES.db
#    - assets/logosmaru/logos_pref.db
